### ISSUE TITLE
Wrong status of assigments is displayed in overview of assignments

### ISSUE THREAD

**Issue by lumbric** [TU-Wien-dataLAB/Grader-Labextension#1]
**Describe the bug**
The status of assignments seems to be wrong in some cases. I will describe one situation here, but I think it is not the only one.

**To Reproduce**
1. Create a new assignment.
2. Release it (agree + commit).
3. Go back to overview of assignments: it says "created" (see first screenshot), but it should say "released", right?
4. Open the assignment and click "undo release"
3. Go back to overview of assignments: it says "released (see second screenshot), but it should say "created", right?

**Expected behavior**

**Screenshots**
Screenshot 1:
![Screenshot 1](https://github.com/TU-Wien-dataLAB/Grader-Service/assets/691772/f8158f8e-7dac-435a-a7ec-988f0c35b917)

Screenshot 2:
![Screenshot 2](https://github.com/TU-Wien-dataLAB/Grader-Service/assets/691772/342f49d1-7597-4592-b32b-93fb6e767325)

**Comment by meffmadd** [comment]
Closing in favor of #27
